TRANSLATIONS = {
    "app_title": {
        "english": 'Community Hub',
        "hindi": 'कम्युनिटी हब',
        "marathi": 'कम्युनिटी हब',
    },
    "app_subtitle": {
        "english": 'Empowering underprivileged communities with opportunities',
        "hindi": 'वंचित समुदायों को अवसरों से सशक्त बनाना',
        "marathi": 'वंचित समुदायांना संधींनी सक्षम करणे',
    },
    "nav_home": {
        "english": 'Home',
        "hindi": 'होम',
        "marathi": 'मुखपृष्ठ',
        "gujarati": 'મુખપૃષ્ઠ',
        "bengali": 'হোম',
        "tamil": 'முகப்பு',
        "telugu": 'హోమ్',
        "punjabi": 'ਮੁੱਖ ਪੰਨਾ',
        "urdu": 'ہوم',
        "odia": 'ହୋମ୍',
        "assamese": 'হোম',
        "nepali": 'गृहपृष्ठ',
        "kannada": 'ಮುಖಪುಟ',
        "malayalam": 'ഹോം',
        "sanskrit": 'मुख्यपृष्ठम्',
        "sindhi": 'هوم',
    },
    "nav_jobs": {
        "english": '💼 Jobs',
        "hindi": '💼 नौकरियां',
        "marathi": '💼 नोकऱ्या',
        "gujarati": '💼 નોકરીઓ',
        "bengali": '💼 চাকরি',
        "tamil": '💼 வேலைகள்',
        "telugu": 'ఉద్యోగాలు',
        "punjabi": '💼 ਨੌਕਰੀਆਂ',
        "urdu": 'نوکریاں',
        "odia": '💼 ଚାକିରି',
        "assamese": '💼 চাকৰি',
        "nepali": '💼 रोजगार',
        "kannada": 'ಉದ್ಯೋಗಗಳು',
        "malayalam": 'ജോലികൾ',
        "sanskrit": 'कार्याणि',
        "sindhi": 'نوڪريون',
    },
    "nav_schemes": {
        "english": '🏛️ Schemes',
        "hindi": '🏛️ योजनाएं',
        "marathi": '🏛️ योजना',
        "gujarati": '🏛️ યોજનાઓ',
        "bengali": '🏛️ স্কিম',
        "tamil": '🏛️ திட்டங்கள்',
        "telugu": 'పథకాలు',
        "punjabi": '🏛️ ਯੋਜਨਾਵਾਂ',
        "urdu": 'اسکیمیں',
        "odia": '🏛️ ଯୋଜନା',
        "assamese": '🏛️ আঁচনি',
        "nepali": '🏛️ योजनाहरू',
        "kannada": 'ಯೋಜನೆಗಳು',
        "malayalam": 'പദ്ധതികൾ',
        "sanskrit": 'योजनाः',
        "sindhi": 'اسڪيمون',
    },
    "nav_resume": {
        "english": '📄 Resume',
        "hindi": '📄 रेज्यूमे',
        "marathi": '📄 रेझ्युमे',
        "punjabi": 'ਰੈਜ਼ਿਊਮੇ',
        "bengali": 'রেজুমে',
        "gujarati": 'રેઝ્યૂમે',
        "tamil": 'ரெஸ்யூம்',
        "telugu": 'రెజ్యూమె',
        "urdu": 'ریزیومے',
        "kannada": 'ರೆಸ್ಯೂಮ್',
        "malayalam": 'ബയോഡാറ്റ',
        "sanskrit": 'वृत्तपत्रम्',
        "sindhi": 'ريزيومي',
    },
    "nav_emergency": {
        "english": '🆘 Emergency',
        "hindi": '🆘 आपातकाल',
        "marathi": '🆘 आणीबाणी',
        "punjabi": 'ਐਮਰਜੈਂਸੀ',
        "bengali": 'জরুরী',
        "gujarati": 'કટોકટી',
        "tamil": 'அவசரம்',
        "telugu": 'అత్యవసర',
        "urdu": 'ایمرجنسی',
        "kannada": 'ತುರ್ತು',
        "malayalam": 'അടിയന്തരാവസ്ഥ',
        "sanskrit": 'आपत्कालीन',
        "sindhi": 'ايمرجنسي',
    },
    "nav_admin": {
        "english": '⚙️ Admin',
        "hindi": '⚙️ एडमिन',
        "marathi": '⚙️ प्रशासन',
        "punjabi": 'ਐਡਮਿਨ',
        "bengali": 'অ্যাডমিন',
        "gujarati": 'એડમિન',
        "tamil": 'நிர்வாகி',
        "telugu": 'అడ్మిన్',
        "urdu": 'ایڈمن',
        "kannada": 'ನಿರ್ವಾಹಕ',
        "malayalam": 'അഡ്മിൻ',
        "sanskrit": 'प्रबन्धकः',
        "sindhi": 'ايڊمن',
    },
    "login": {
        "english": 'Login',
        "hindi": 'लॉगिन',
        "marathi": 'लॉगिन',
        "punjabi": 'ਲਾਗਿਨ',
        "bengali": 'লগইন',
        "gujarati": 'લૉગિન',
        "tamil": 'உள்நுழை',
        "telugu": 'లాగిన్',
        "urdu": 'لاگ ان',
        "kannada": 'ಲಾಗಿನ್',
        "malayalam": 'ലോഗിൻ',
        "sanskrit": 'प्रवेशः',
        "sindhi": 'لاگ ان',
    },
    "register": {
        "english": 'Register',
        "hindi": 'पंजीकरण',
        "marathi": 'नोंदणी',
        "punjabi": 'ਰਜਿਸਟਰ',
        "bengali": 'নিবন্ধন',
        "gujarati": 'નોંધણી',
        "tamil": 'பதிவு',
        "telugu": 'నమోదు',
        "urdu": 'رجسٹر',
        "kannada": 'ನೋಂದಣಿ',
        "malayalam": 'രജിസ്റ്റർ',
        "sanskrit": 'पञ्जीकरणम्',
        "sindhi": 'رجسٽر',
    },
    "nav_logout": {
        "english": '🚪 Logout',
        "hindi": '🚪 लॉगआउट',
        "marathi": '🚪 बाहेर पडा',
    },
    "logout": {
        "english": '🚪 Logout',
        "hindi": 'लॉगआउट',
        "marathi": 'बाहेर पडा',
        "punjabi": 'ਲਾਗਆਊਟ',
        "bengali": 'লগআউট',
        "gujarati": 'લૉગઆઉટ',
        "tamil": 'வெளியேறு',
        "telugu": 'లాగౌట్',
        "urdu": 'لاگ آؤٹ',
        "kannada": 'ಲಾಗೌಟ್',
        "malayalam": 'ലോഗൗട്ട്',
        "sanskrit": 'निर्गमः',
        "sindhi": 'لاگ آئوٽ',
    },
    "hero_title": {
        "english": 'Connecting Communities with Jobs, Skills, Schemes & Support.',
        "hindi": 'समुदायों को नौकरी, कौशल, योजनाओं और सहायता से जोड़ना।',
        "marathi": 'समुदायांना नोकऱ्या, कौशल्ये, योजना आणि सहाय्याशी जोडणे.',
        "punjabi": 'ਸਮੁਦਾਇਆਂ ਨੂੰ ਨੌਕਰੀਆਂ, ਹੁਨਰ, ਯੋਜਨਾਵਾਂ ਅਤੇ ਮਦਦ ਨਾਲ ਜੋੜਨਾ।',
        "bengali": 'সম্প্রদায়গুলিকে চাকরি, দক্ষতা, স্কিম এবং সহায়তার সাথে সংযুক্ত করা।',
        "gujarati": 'સમુદાયોને નોકરીઓ, કૌશલ્યો, યોજનાઓ અને સહાય સાથે જોડવું.',
        "tamil": 'சமூகங்களை வேலைகள், திறன்கள், திட்டங்கள் மற்றும் ஆதரவுடன் இணைக்கிறது.',
        "telugu": 'సముదాయాలను ఉద్యోగాలు, నైపుణ్యాలు, పథకాలు మరియు సహాయంతో అనుసంధానించడం.',
        "urdu": 'کمیونٹیز کو نوکریوں، مہارتوں، اسکیموں اور امداد سے جوڑنا۔',
        "kannada": 'ಸಮುದಾಯಗಳನ್ನು ಉದ್ಯೋಗಗಳು, ಕೌಶಲ್ಯಗಳು, ಯೋಜನೆಗಳು ಮತ್ತು ಬೆಂಬಲದೊಂದಿಗೆ ಸಂಪರ್ಕಿಸುವುದು.',
        "malayalam": 'സമൂഹങ്ങളെ ജോലികൾ, കഴിവുകൾ, പദ്ധതികൾ, പിന്തുണ എന്നിവയുമായി ബന്ധിപ്പിക്കുന്നു.',
        "sanskrit": 'समुदायान् कार्यैः, कौशलैः, योजनाभिः साहाय्येन च योजयन्।',
        "sindhi": 'برادرين کي نوڪرين، مهارتن، اسڪيمن ۽ امداد سان ڳنڍڻ.',
    },
    "stat_jobs": {
        "english": 'Job Listings',
        "hindi": 'नौकरी सूचियां',
        "marathi": 'नोकरी याद्या',
        "punjabi": 'ਨੌਕਰੀਆਂ ਦੀ ਸੂਚੀ',
        "bengali": 'চাকরির তালিকা',
        "gujarati": 'નોકરીઓની યાદી',
        "tamil": 'வேலை பட்டியல்கள்',
        "telugu": 'ఉద్యోగాల జాబితాలు',
        "urdu": 'نوکریوں کی فہرست',
        "kannada": 'ಉದ್ಯೋಗ ಪಟ್ಟಿಗಳು',
        "malayalam": 'തൊഴിൽ ലിസ്റ്റിംഗുകൾ',
        "sanskrit": 'कार्यसूच्यः',
        "sindhi": 'نوڪرين جي فهرست',
    },
    "stat_schemes": {
        "english": 'Govt Schemes',
        "hindi": 'सरकारी योजनाएं',
        "marathi": 'सरकारी योजना',
        "punjabi": 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
        "bengali": 'সরকারি স্কিম',
        "gujarati": 'સરકારી યોજનાઓ',
        "tamil": 'அரசு திட்டங்கள்',
        "telugu": 'ప్రభుత్వ పథకాలు',
        "urdu": 'سرکاری اسکیمیں',
        "kannada": 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
        "malayalam": 'സർക്കാർ പദ്ധതികൾ',
        "sanskrit": 'सर्वकारीय-योजनाः',
        "sindhi": 'سرڪاري اسڪيمون',
    },
    "stat_ngos": {
        "english": 'NGOs & Hospitals',
        "hindi": 'NGOs और अस्पताल',
        "marathi": 'NGOs आणि रुग्णालये',
        "punjabi": 'NGO ਅਤੇ ਹਸਪਤਾਲ',
        "bengali": 'এনজিও এবং হাসপাতাল',
        "gujarati": 'NGO અને હોસ્પિટલો',
        "tamil": 'தன்னார்வ தொண்டு நிறுவனங்கள் & மருத்துவமனைகள்',
        "telugu": 'ఎన్\u200cజిఓలు & ఆసుపత్రులు',
        "urdu": 'این جی اوز اور اسپتال',
        "kannada": 'ಎನ್\u200cಜಿಒಗಳು ಮತ್ತು ಆಸ್ಪತ್ರೆಗಳು',
        "malayalam": 'എൻ\u200cജി\u200cഒകളും ആശുപത്രികളും',
        "sanskrit": 'स्वयंसेवी संस्थाः एवं चिकित्सालयाः',
        "sindhi": 'اين جي اوز ۽ اسپتالون',
    },
    "stat_users": {
        "english": 'People Helped',
        "hindi": 'लोगों की मदद',
        "marathi": 'लोकांना मदत',
        "punjabi": 'ਲੋਕਾਂ ਦੀ ਮਦਦ ਕੀਤੀ',
        "bengali": 'মানুষকে সাহায্য করা হয়েছে',
        "gujarati": 'લોકોને મદદ કરી',
        "tamil": 'உதவி செய்யப்பட்ட மக்கள்',
        "telugu": 'సహాయం పొందిన ప్రజలు',
        "urdu": 'مدد حاصل کرنے والے افراد',
        "kannada": 'ಸಹಾಯ ಪಡೆದ ಜನರು',
        "malayalam": 'സഹായം ലഭിച്ച ആളുകൾ',
        "sanskrit": 'साहाय्यं प्राप्ताः जनाः',
        "sindhi": 'مدد حاصل ڪندڙ ماڻهو',
    },
    "feat_job_title": {
        "english": 'AI Job Matching',
        "hindi": 'AI नौकरी मिलान',
        "marathi": 'AI नोकरी जुळवणी',
        "punjabi": 'AI ਨੌਕਰੀ ਮੇਲ',
        "bengali": 'এআই চাকরি ম্যাচিং',
        "gujarati": 'AI નોકરી મેચિંગ',
        "tamil": 'AI வேலை பொருத்தம்',
        "telugu": 'AI ఉద్యోగ సరిపోలిక',
        "urdu": 'AI جاب میچنگ',
        "kannada": 'AI ಉದ್ಯೋಗ ಹೊಂದಾಣಿಕೆ',
        "malayalam": 'AI ജോബ് മാച്ചിംഗ്',
        "sanskrit": 'ए.आई कार्य-योजनम्',
        "sindhi": 'AI جاب ميچنگ',
    },
    "feat_job_desc": {
        "english": 'Smart skill-based job matching using AI. Find jobs that fit your skills.',
        "hindi": 'AI का उपयोग करके स्मार्ट कौशल-आधारित नौकरी मिलान।',
        "marathi": 'AI वापरून स्मार्ट कौशल्य-आधारित नोकरी जुळवणी.',
        "punjabi": 'AI ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਹੁਨਰ-ਅਧਾਰਤ ਨੌਕਰੀ ਦੀ ਭਾਲ।',
        "bengali": 'এআই ব্যবহার করে স্কিল-ভিত্তিক চাকরি খোঁজা।',
        "gujarati": 'AI નો ઉપયોગ કરીને કૌશલ્ય આધારિત નોકરીની શોધ.',
        "tamil": 'AI ஐப் பயன்படுத்தி திறன் அடிப்படையிலான வேலை தேடல்.',
        "telugu": 'AI ని ఉపయోగించి నైపుణ్య-ఆధారిత ఉద్యోగ సరిపోలిక.',
        "urdu": 'AI کا استعمال کرتے ہوئے ہنر پر مبنی نوکری کی تلاش۔',
        "kannada": 'AI ಬಳಸಿಕೊಂಡು ಕೌಶಲ್ಯ ಆಧಾರಿತ ಉದ್ಯೋಗ ಹೊಂದಾಣಿಕೆ.',
        "malayalam": 'AI ഉപയോഗിച്ച് നൈപുണ്യ അടിസ്ഥാനമാക്കിയുള്ള ജോലി പൊരുത്തപ്പെടുത്തൽ.',
        "sanskrit": 'ए.आई इत्यस्य उपयोगेन कौशल-आधारितं कार्य-अन्वेषणम्।',
        "sindhi": 'AI جو استعمال ڪندي مهارت تي ٻڌل نوڪري جي ڳولا.',
    },
    "feat_scheme_title": {
        "english": 'Govt Scheme Finder',
        "hindi": 'सरकारी योजना खोजक',
        "marathi": 'सरकारी योजना शोधक',
        "punjabi": 'ਸਰਕਾਰੀ ਯੋਜਨਾ ਖੋਜਕ',
        "bengali": 'সরকারি স্কিম ফাইন্ডার',
        "gujarati": 'સરકારી યોજના શોધક',
        "tamil": 'அரசு திட்டம் கண்டுபிடிப்பாளர்',
        "telugu": 'ప్రభుత్వ పథకం ఫైండర్',
        "urdu": 'سرکاری اسکیم فائنڈر',
        "kannada": 'ಸರ್ಕಾರಿ ಯೋಜನೆ ಶೋಧಕ',
        "malayalam": 'സർക്കാർ പദ്ധതി ഫൈൻഡർ',
        "sanskrit": 'सर्वकारीय-योजना-अन्वेषकः',
        "sindhi": 'سرڪاري اسڪيم فائنڊر',
    },
    "feat_scheme_desc": {
        "english": "Discover government schemes you're eligible for based on your profile.",
        "hindi": 'अपनी प्रोफ़ाइल के आधार पर सरकारी योजनाओं का पता लगाएं।',
        "marathi": 'तुमच्या प्रोफाइलनुसार पात्र योजना शोधा.',
        "punjabi": 'ਆਪਣੇ ਪ੍ਰੋਫਾਈਲ ਦੇ ਅਧਾਰ ਤੇ ਯੋਜਨਾਵਾਂ ਲੱਭੋ।',
        "bengali": 'আপনার প্রোফাইলের উপর ভিত্তি করে স্কিম খুঁজুন।',
        "gujarati": 'તમારી પ્રોફાઇલના આધારે યોજનાઓ શોધો.',
        "tamil": 'உங்கள் சுயவிவரத்தின் அடிப்படையில் திட்டங்களைக் கண்டறியவும்.',
        "telugu": 'మీ ప్రొఫైల్ ఆధారంగా పథకాలను కనుగొనండి.',
        "urdu": 'اپنے پروفائل کی بنیاد پر اسکیمیں تلاش کریں۔',
        "kannada": 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಆಧಾರದ ಮೇಲೆ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ.',
        "malayalam": 'നിങ്ങളുടെ പ്രൊഫൈൽ അടിസ്ഥാനമാക്കി പദ്ധതികൾ കണ്ടെത്തുക.',
        "sanskrit": 'भवताम् विवरणानुसारं योजनाः अन्विष्यन्तु।',
        "sindhi": 'پنهنجي پروفائل جي بنياد تي اسڪيمون ڳوليو.',
    },
    "feat_resume_title": {
        "english": 'Resume Generator',
        "hindi": 'रेज्यूमे जनरेटर',
        "marathi": 'रेझ्युमे जनरेटर',
        "punjabi": 'ਰੈਜ਼ਿਊਮੇ ਜਨਰੇਟਰ',
        "bengali": 'রেজুমে জেনারেটর',
        "gujarati": 'રેઝ્યૂમે જનરેટર',
        "tamil": 'ரெஸ்யூம் ஜெனரேட்டர்',
        "telugu": 'రెజ్యూమె జనరేటర్',
        "urdu": 'ریزیومے جنریٹر',
        "kannada": 'ರೆಸ್ಯೂಮ್ ಜನರೇಟರ್',
        "malayalam": 'റെസ്യൂം ജനറേറ്റർ',
        "sanskrit": 'वृत्तपत्र-निर्माता',
        "sindhi": 'ريزيومي جنريٽر',
    },
    "feat_resume_desc": {
        "english": 'Generate a professional PDF resume instantly with your details.',
        "hindi": 'अपने विवरण से तुरंत PDF रेज्यूमे बनाएं।',
        "marathi": 'तुमच्या माहितीसह तत्काळ PDF रेझ्युमे तयार करा.',
        "telugu": 'మీ వివరాలతో తక్షణమే PDF రెజ్యూమెను రూపొందించండి.',
        "urdu": 'اپنی تفصیلات کے ساتھ فوری طور پر PDF ریزیومے بنائیں۔',
        "kannada": 'ನಿಮ್ಮ ವಿವರಗಳೊಂದಿಗೆ ತಕ್ಷಣವೇ PDF ರೆಸ್ಯೂಮ್ ರಚಿಸಿ.',
        "malayalam": 'നിങ്ങളുടെ വിവരങ്ങൾ ഉപയോഗിച്ച് ഉടനടി PDF ബയോഡാറ്റ നിർമ്മിക്കുക.',
        "sanskrit": 'स्व-विवरणैः सह तत्क्षणमेव PDF वृत्तपत्रं निर्मियताम्।',
        "sindhi": 'پنهنجي تفصيلن سان فوري طور تي PDF ريزيومي ٺاهيو.',
    },
    "feat_skillgap_title": {
        "english": 'Skill Gap Analysis',
        "hindi": 'स्किल गैप एनालिसिस',
        "marathi": 'स्किल गॅप ॲनालिसिस',
        "gujarati": 'સ્કિલ ગેપ એનાલિસિસ',
        "bengali": 'স্কিল গ্যাপ অ্যানালিসিস',
        "tamil": 'திறன் இடைவெளி பகுப்பாய்வு',
        "telugu": 'స్కిల్ గ్యాప్ విశ్లేషణ',
        "punjabi": 'ਹੁਨਰ ਗੈਪ ਵਿਸ਼ਲੇਸ਼ਣ',
        "urdu": 'اسکل گیپ تجزیہ',
        "kannada": 'ಸ್ಕಿಲ್ ಗ್ಯಾಪ್ ವಿಶ್ಲೇಷಣೆ',
        "malayalam": 'സ്‌കിൽ ഗ്യാപ് വിശകലനം',
        "sanskrit": 'कौशल-अन्तर-विश्लेषणम्',
        "sindhi": 'اسڪل گيپ تجزيو',
    },
    "feat_skillgap_desc": {
        "english": 'Analyze missing skills for target jobs & get matched learning resources.',
        "hindi": 'लक्ष्य नौकरियों के लिए छूटे हुए कौशलों का विश्लेषण करें और कोर्स पाएं।',
        "marathi": 'टारगेट जॉब्ससाठी आवश्यक कौशल्ये शोधा आणि मोफत कोर्सेस मिळवा.',
        "telugu": 'లక్ష్య ఉద్యోగాల కోసం మిస్సింగ్ నైపుణ్యాలను విశ్లేషించండి.',
        "urdu": 'ٹارگٹ جابز کے لیے غائب ہنر کا تجزیہ کریں اور مفت کورسز حاصل کریں۔',
        "kannada": 'ಉದ್ಯೋಗಗಳಿಗೆ ಅಗತ್ಯವಿರುವ ಕೌಶಲ್ಯಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ ಮತ್ತು ಕೋರ್ಸ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ.',
        "malayalam": 'ലക്ഷ്യ ജോലികൾക്കായി ആവശ്യമായ കഴിവുകൾ വിശകലനം ചെയ്യുക.',
        "sanskrit": 'लक्ष्य-कार्याणां कृते आवश्यक-कौशल-अन्वेषणम्।',
        "sindhi": 'ٽارگيٽ نوڪرين لاءِ گهربل مهارتون تجزيو ڪريو.',
    },
    "feat_emergency_title": {
        "english": 'Emergency Help',
        "hindi": 'आपातकालीन सहायता',
        "marathi": 'आणीबाणी मदत',
        "punjabi": 'ਐਮਰਜੈਂਸੀ ਮਦਦ',
        "bengali": 'জরুরী সাহায্য',
        "gujarati": 'કટોકટી મદદ',
        "tamil": 'அவசர உதவி',
        "telugu": 'అత్యవసర సహాయం',
        "urdu": 'ایمرجنسی مدد',
        "kannada": 'ತುರ್ತು ಸಹಾಯ',
        "malayalam": 'അടിയന്തര സഹായം',
        "sanskrit": 'आपत्कालीन-साहाय्यम्',
        "sindhi": 'ايمرجنسي مدد',
    },
    "feat_emergency_desc": {
        "english": 'Find nearby NGOs, hospitals, and helplines in one click.',
        "hindi": 'एक क्लिक में नजदीकी NGO, अस्पताल और हेल्पलाइन खोजें।',
        "marathi": 'एका क्लिकमध्ये जवळचे NGO, रुग्णालये आणि हेल्पलाइन शोधा.',
        "telugu": 'ఒకే క్లిక్\u200cతో సమీప ఎన్\u200cజిఓలు, ఆసుపత్రులు మరియు హెల్ప్\u200cలైన్\u200cలను కనుగొనండి.',
        "urdu": 'ایک کلک میں قریبی این جی اوز، اسپتال اور ہیلپ لائنز تلاش کریں۔',
        "kannada": 'ಒಂದೇ ಕ್ಲಿಕ್\u200cನಲ್ಲಿ ಹತ್ತಿರದ ಎನ್\u200cಜಿಒಗಳು, ಆಸ್ಪತ್ರೆಗಳು ಮತ್ತು ಸಹಾಯವಾಣಿಗಳನ್ನು ಹುಡುಕಿ.',
        "malayalam": 'ഒറ്റ ക്ലിക്കിൽ അടുത്തുള്ള എൻ\u200cജി\u200cഒകൾ, ആശുപത്രികൾ, ഹെൽപ്പ് ലൈനുകൾ എന്നിവ കണ്ടെത്തുക.',
        "sanskrit": 'एकस्मिन् क्लिक्-माध्यमेन समीपस्थान् चिकित्सालयान्, साहाय्यकेन्द्राणि च पश्यन्तु।',
        "sindhi": 'هڪ ڪلڪ ۾ ويجها اين جي اوز، اسپتالون ۽ هيلپ لائنون ڳوليو.',
    },
    "please_login": {
        "english": 'Please login first.',
        "hindi": 'कृपया पहले लॉगिन करें।',
        "marathi": 'कृपया आधी लॉगिन करा.',
    },
    "name": {
        "english": 'Full Name',
        "hindi": 'पूरा नाम',
        "marathi": 'पूर्ण नाव',
    },
    "age": {
        "english": 'Age',
        "hindi": 'आयु',
        "marathi": 'वय',
    },
    "phone": {
        "english": 'Mobile Number',
        "hindi": 'मोबाइल नंबर',
        "marathi": 'मोबाइल नंबर',
    },
    "password": {
        "english": 'Password',
        "hindi": 'पासवर्ड',
        "marathi": 'पासवर्ड',
    },
    "location": {
        "english": 'Location / Area',
        "hindi": 'स्थान / क्षेत्र',
        "marathi": 'स्थान / परिसर',
    },
    "district": {
        "english": 'District',
        "hindi": 'जिला',
        "marathi": 'जिल्हा',
    },
    "skills": {
        "english": 'Skills (comma separated)',
        "hindi": 'कौशल (कॉमा से अलग)',
        "marathi": 'कौशल्ये (स्वल्पविरामाने वेगळे करा)',
    },
    "education": {
        "english": 'Education Level',
        "hindi": 'शिक्षा स्तर',
        "marathi": 'शिक्षण स्तर',
    },
    "income": {
        "english": 'Monthly Income (₹)',
        "hindi": 'मासिक आय (₹)',
        "marathi": 'मासिक उत्पन्न (₹)',
    },
    "gender": {
        "english": 'Gender',
        "hindi": 'लिंग',
        "marathi": 'लिंग',
    },
    "caste": {
        "english": 'Category',
        "hindi": 'श्रेणी',
        "marathi": 'श्रेणी',
    },
    "submit": {
        "english": 'Submit',
        "hindi": 'जमा करें',
        "marathi": 'सबमिट करा',
    },
    "welcome": {
        "english": 'Welcome',
        "hindi": 'स्वागत है',
        "marathi": 'स्वागत आहे',
    },
    "nav_skillgap": {
        "english": '📈 Skill Gap',
        "hindi": '📈 कौशल अंतर',
        "marathi": '📈 कौशल्य अंतर',
    },
    "sg_title": {
        "english": 'Skill Gap Analysis',
        "hindi": 'कौशल अंतर विश्लेषण',
        "marathi": 'कौशल्य अंतर विश्लेषण',
    },
    "sg_desc": {
        "english": 'Find out which skills you are missing and learn them for free.',
        "hindi": 'जानें कि आपमें किन कौशलों की कमी है और उन्हें मुफ्त में सीखें।',
        "marathi": 'तुमच्यात कोणत्या कौशल्यांची कमतरता आहे ते शोधा आणि ती विनामूल्य शिका.',
    },
    "sg_select_job": {
        "english": 'Select a Target Job',
        "hindi": 'एक लक्ष्य नौकरी चुनें',
        "marathi": 'लक्षित नोकरी निवडा',
    },
    "sg_best_matches": {
        "english": 'Best matches for me',
        "hindi": 'मेरे लिए सर्वश्रेष्ठ नौकरियां',
        "marathi": 'माझ्यासाठी सर्वोत्तम नोकऱ्या',
    },
    "sg_your_skills": {
        "english": 'Skills You Have',
        "hindi": 'आपके कौशल',
        "marathi": 'तुमची कौशल्ये',
    },
    "sg_missing_skills": {
        "english": 'Missing Skills',
        "hindi": 'अनुपस्थित कौशल',
        "marathi": 'नसलेली कौशल्ये',
    },
    "sg_learn": {
        "english": 'Learn',
        "hindi": 'सीखें',
        "marathi": 'शिका',
    },
    "sg_improves_match_to": {
        "english": 'improves match to',
        "hindi": 'मैच बढ़ाएगा',
        "marathi": 'साम्य वाढवेल',
    },
    "sg_suggested_courses": {
        "english": 'Suggested Free Courses',
        "hindi": 'सुझाए गए मुफ्त पाठ्यक्रम',
        "marathi": 'सुचवलेले मोफत अभ्यासक्रम',
    },
    "sg_no_missing": {
        "english": 'You have all the required skills!',
        "hindi": 'आपके पास सभी आवश्यक कौशल हैं!',
        "marathi": 'तुमच्याकडे सर्व आवश्यक कौशल्ये आहेत!',
    },
    "sg_no_courses": {
        "english": 'No courses found for this skill.',
        "hindi": 'इस कौशल के लिए कोई पाठ्यक्रम नहीं मिला।',
        "marathi": 'या कौशल्यासाठी कोणताही अभ्यासक्रम सापडला नाही.',
    },
    "nav_chatbot": {
        "english": '🎙️ AI Assistant',
        "hindi": '🎙️ एआई सहायक',
        "marathi": '🎙️ एआय सहाय्यक',
    },
    "cb_title": {
        "english": 'AI Voice Assistant',
        "hindi": 'एआई वॉयस असिस्टेंट',
        "marathi": 'एआय व्हॉईस असिस्टंट',
    },
    "cb_desc": {
        "english": 'Click the mic and ask a question in your language.',
        "hindi": 'माइक पर क्लिक करें और अपनी भाषा में सवाल पूछें।',
        "marathi": 'माइकवर क्लिक करा आणि तुमच्या भाषेत प्रश्न विचारा.',
    },
    "cb_api_prompt": {
        "english": 'Enter Gemini API Key (Admin/Setup)',
        "hindi": 'Gemini API Key दर्ज करें',
        "marathi": 'Gemini API Key प्रविष्ट करा',
    },
    "cb_save_key": {
        "english": 'Save Key',
        "hindi": 'की सेव करें',
        "marathi": 'Key जतन करा',
    },
    "cb_tip": {
        "english": 'Click the mic (🎙️) button on your mobile keyboard to ask by speaking.',
        "hindi": 'बोलकर सवाल पूछने के लिए अपने मोबाइल कीबोर्ड पर माइक (🎙️) बटन पर क्लिक करें।',
        "marathi": 'बोलून प्रश्न विचारण्यासाठी तुमच्या मोबाईल कीबोर्डवरील माइक (🎙️) बटणावर क्लिक करा.',
    },
    "cb_input_placeholder": {
        "english": 'Type or speak your question here...',
        "hindi": 'अपना सवाल यहाँ लिखें या बोलें...',
        "marathi": 'तुमचा प्रश्न येथे लिहा किंवा बोला...',
    },
    "feat_tracker_title": {
        "english": 'Application Tracker',
        "hindi": 'आवेदन ट्रैकर',
        "marathi": 'अर्ज ट्रॅकर',
    },
    "feat_tracker_desc": {
        "english": 'Track status of all your applications — Applied, Interview, Selected',
        "hindi": 'अपने सभी आवेदनों की स्थिति ट्रैक करें — लागू, साक्षात्कार, चयनित',
        "marathi": 'तुमच्या सर्व अर्जांची स्थिती ट्रॅक करा — लागू, मुलाखत, निवडलेले',
    },
    "feat_courses_title": {
        "english": 'Free Skill Courses',
        "hindi": 'मुफ्त कौशल पाठ्यक्रम',
        "marathi": 'मोफत कौशल्य अभ्यासक्रम',
    },
    "feat_courses_desc": {
        "english": '12+ free courses from PMKVY & Skill India with skill matching',
        "hindi": 'PMKVY और स्किल इंडिया के 12+ मुफ़्त पाठ्यक्रम — कौशल मिलान के साथ',
        "marathi": 'PMKVY आणि स्किल इंडियाचे १२+ मोफत अभ्यासक्रम — कौशल्य जुळवणीसह',
    },
    "nav_tracker": {
        "english": '📊 Tracker',
        "hindi": '📊 ट्रैकर',
        "marathi": '📊 ट्रॅकर',
    },
    "nav_courses": {
        "english": '🎓 Courses',
        "hindi": '🎓 पाठ्यक्रम',
        "marathi": '🎓 अभ्यासक्रम',
    },
    "nav_alerts": {
        "english": '🔔 Alerts',
        "hindi": '🔔 अलर्ट',
        "marathi": '🔔 सूचना',
    },
    "nav_profile": {
        "english": '👤 Profile',
        "hindi": '👤 प्रोफ़ाइल',
        "marathi": '👤 प्रोफाइल',
    },
    "feat_chatbot_title": {
        "english": 'AI Voice Assistant',
        "hindi": 'एआई वॉयस असिस्टेंट',
        "marathi": 'एआय व्हॉईस असिस्टंट',
    },
    "feat_chatbot_desc": {
        "english": 'Ask questions about jobs, schemes & emergency in your language',
        "hindi": 'अपनी भाषा में नौकरी, योजनाओं और आपातकाल के बारे में सवाल पूछें',
        "marathi": 'तुमच्या भाषेत नोकरी, योजना आणि आणीबाणीबद्दल प्रश्न विचारा',
    },
}

def get_text(key, lang="english"):
    return TRANSLATIONS.get(key, {}).get(lang, TRANSLATIONS.get(key, {}).get("english", key))

def set_language(lang):
    pass
